"""balancemodels

Revision ID: 11e0ca5aa579
Revises: 5f79bb132b52
Create Date: 2023-08-30 14:30:25.477739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e0ca5aa579'
down_revision = '5f79bb132b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchasebalancepayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('given', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['purchase'], ['purchase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salesbalancepayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('given_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sales'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('purchase', sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('purchase', sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('purchase', sa.Column('given', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('sale_products', sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('sale_products', sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('sale_products', sa.Column('given_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_products', 'given_amount')
    op.drop_column('sale_products', 'total')
    op.drop_column('sale_products', 'balance')
    op.drop_column('purchase', 'given')
    op.drop_column('purchase', 'total')
    op.drop_column('purchase', 'balance')
    op.drop_table('salesbalancepayment')
    op.drop_table('purchasebalancepayment')
    # ### end Alembic commands ###
