"""textfield changes

Revision ID: 41451d2a8480
Revises: 91c7582347e1
Create Date: 2023-08-25 15:01:49.590735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41451d2a8480'
down_revision = '91c7582347e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
