"""balancemodels2

Revision ID: 476e6412747a
Revises: 11e0ca5aa579
Create Date: 2023-09-01 11:39:44.762183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476e6412747a'
down_revision = '11e0ca5aa579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sale_products_mobile_number_key', 'sale_products', type_='unique')
    op.drop_column('sale_products', 'total')
    op.drop_column('sale_products', 'mobile_number')
    op.drop_column('sale_products', 'balance')
    op.drop_column('sale_products', 'given_amount')
    op.add_column('sales', sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('sales', sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('sales', sa.Column('given_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_constraint('sales_mobile_number_key', 'sales', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sales_mobile_number_key', 'sales', ['mobile_number'])
    op.drop_column('sales', 'given_amount')
    op.drop_column('sales', 'total')
    op.drop_column('sales', 'balance')
    op.add_column('sale_products', sa.Column('given_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('sale_products', sa.Column('balance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('sale_products', sa.Column('mobile_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sale_products', sa.Column('total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.create_unique_constraint('sale_products_mobile_number_key', 'sale_products', ['mobile_number'])
    # ### end Alembic commands ###
