"""unique in product

Revision ID: 5f79bb132b52
Revises: 41451d2a8480
Create Date: 2023-08-28 10:06:10.680551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f79bb132b52'
down_revision = '41451d2a8480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_name_sub_category', 'product', type_='unique')
    op.create_unique_constraint('uq_brand_name_sub_category', 'product', ['category', 'sub_category', 'brand', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_brand_name_sub_category', 'product', type_='unique')
    op.create_unique_constraint('uq_name_sub_category', 'product', ['name', 'sub_category'])
    # ### end Alembic commands ###
