"""agency

Revision ID: aa2c782bab23
Revises: 7d83ef7ba903
Create Date: 2023-08-21 09:31:54.648661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa2c782bab23'
down_revision = '7d83ef7ba903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
